fix: goreleaser
Signed-off-by: Alexander Sharov <kvendingoldo@yandex.ru>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -70,6 +70,20 @@ jobs:
             cp .goreleaser.yml .goreleaser_ci.yml
           fi
 
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # ratchet:docker/login-action@v4.2.0
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # ratchet:docker/login-action@v4.2.0
+        with:
+          registry: registry.hub.docker.com
+          username: ${{ secrets.REGISTRY_USER }}
+          password: ${{ secrets.REGISTRY_PASSWORD }}
+
       - name: Run GoReleaser
         uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89
         with:
@@ -90,83 +104,71 @@ jobs:
           CLOUDSMITH_TOKEN: ${{ secrets.CLOUDSMITH_TOKEN }}
           TOFUUTILS_PR_TOKEN: ${{ secrets.TOFUUTILS_PR_TOKEN }}
 
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # ratchet:docker/login-action@v4.2.0
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Push docker image to GitHub Container Registry
-        env:
-          docker_registry: "ghcr.io"
-        run: |
-          version=${GITHUB_REF#refs/*/v}
-          IFS='.' read -ra version_arr <<< "${version}"
 
-          architectures=("amd64" "arm64" "arm" "386")
-          versions=("latest" "${version_arr[0]}.${version_arr[1]}" "${version}")
-
-          for version in "${versions[@]}"; do
-            manifest="${docker_registry}/tofuutils/tenv:${version}"
-            images=""
-
-            for arch in "${architectures[@]}"; do
-              image="${docker_registry}/tofuutils/tenv:${version}-${arch}"
-              echo "Pushing image ${image} ..."
-              docker push ${image}
-              if [ ${?} -ne 0 ]; then
-                echo "Failed to push image ${image}"
-                exit 1
-              fi
-              images="${image} ${images}"
-            done
-
-            docker manifest create "${manifest}" ${images}
-            docker manifest push "${manifest}"
-
-          done
-
-          echo "All images and manifests pushed successfully to ${docker_registry}!"
-
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # ratchet:docker/login-action@v4.2.0
-        with:
-          registry: registry.hub.docker.com
-          username: ${{ secrets.REGISTRY_USER }}
-          password: ${{ secrets.REGISTRY_PASSWORD }}
-
-      - name: Push docker image to DockerHub
-        env:
-          docker_registry: "registry.hub.docker.com"
-        run: |
-          version=${GITHUB_REF#refs/*/v}
-          IFS='.' read -ra version_arr <<< "${version}"
-
-          architectures=("amd64" "arm64" "arm" "386")
-          versions=("latest" "${version_arr[0]}.${version_arr[1]}" "${version}")
-
-          for version in "${versions[@]}"; do
-            manifest="${docker_registry}/tofuutils/tenv:${version}"
-            images=""
-
-            for arch in "${architectures[@]}"; do
-              image="${docker_registry}/tofuutils/tenv:${version}-${arch}"
-              echo "Pushing image ${image} ..."
-              docker push ${image}
-              if [ ${?} -ne 0 ]; then
-                echo "Failed to push image ${image}"
-                exit 1
-              fi
-              images="${image} ${images}"
-            done
-
-            docker manifest create "${manifest}" ${images}
-            docker manifest push "${manifest}"
-
-          done
-
-          echo "All images and manifests pushed successfully to ${docker_registry}!"
+#      - name: Push docker image to GitHub Container Registry
+#        env:
+#          docker_registry: "ghcr.io"
+#        run: |
+#          version=${GITHUB_REF#refs/*/v}
+#          IFS='.' read -ra version_arr <<< "${version}"
+#
+#          architectures=("amd64" "arm64" "arm" "386")
+#          versions=("latest" "${version_arr[0]}.${version_arr[1]}" "${version}")
+#
+#          for version in "${versions[@]}"; do
+#            manifest="${docker_registry}/tofuutils/tenv:${version}"
+#            images=""
+#
+#            for arch in "${architectures[@]}"; do
+#              image="${docker_registry}/tofuutils/tenv:${version}-${arch}"
+#              echo "Pushing image ${image} ..."
+#              docker push ${image}
+#              if [ ${?} -ne 0 ]; then
+#                echo "Failed to push image ${image}"
+#                exit 1
+#              fi
+#              images="${image} ${images}"
+#            done
+#
+#            docker manifest create "${manifest}" ${images}
+#            docker manifest push "${manifest}"
+#
+#          done
+#
+#          echo "All images and manifests pushed successfully to ${docker_registry}!"
+#
+#      - name: Push docker image to DockerHub
+#        env:
+#          docker_registry: "registry.hub.docker.com"
+#        run: |
+#          version=${GITHUB_REF#refs/*/v}
+#          IFS='.' read -ra version_arr <<< "${version}"
+#
+#          architectures=("amd64" "arm64" "arm" "386")
+#          versions=("latest" "${version_arr[0]}.${version_arr[1]}" "${version}")
+#
+#          for version in "${versions[@]}"; do
+#            manifest="${docker_registry}/tofuutils/tenv:${version}"
+#            images=""
+#
+#            for arch in "${architectures[@]}"; do
+#              image="${docker_registry}/tofuutils/tenv:${version}-${arch}"
+#              echo "Pushing image ${image} ..."
+#              docker push ${image}
+#              if [ ${?} -ne 0 ]; then
+#                echo "Failed to push image ${image}"
+#                exit 1
+#              fi
+#              images="${image} ${images}"
+#            done
+#
+#            docker manifest create "${manifest}" ${images}
+#            docker manifest push "${manifest}"
+#
+#          done
+#
+#          echo "All images and manifests pushed successfully to ${docker_registry}!"
 
   publish-chocolatey:
     name: "Publish Chocolatey package"
